name: trenergy_wallet
description: "A new Flutter project."

publish_to: 'none'

version: 0.0.6+6

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  animate_do: ^3.3.4
  animated_transform: ^1.0.5
  audioplayers: ^6.0.0
  auto_size_text_field: ^2.2.3
  base58check: ^2.0.0
  bip39: ^1.0.6
  blockchain_utils: ^2.1.1
  bs58check: ^1.0.2
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.1
  cupertino_icons: ^1.0.6
  device_info_plus: ^10.0.1
  dio: ^5.4.2
  easy_localization: ^3.0.5
  encrypt: ^5.0.3
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.2
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  flutter_local_notifications: ^16.1.0
  flutter_localized_locales: ^2.0.5
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.5
  freezed_annotation: ^2.4.1
  go_router: ^13.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.5.1
  http: ^1.0.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  on_chain: ^3.0.1
  package_info_plus: ^8.0.0
  pretty_qr_code: ^3.3.0
  pull_to_refresh_notification: ^3.1.0
  retrofit: ^4.1.0
  rive: ^0.13.1
  riverpod_annotation: ^2.3.5
  share_plus: ^8.0.3
  url_launcher: ^6.2.5
  visibility_detector: ^0.4.0+2
  wallet: ^0.0.13
  week_of_year: ^2.2.0


dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  meta: ^1.12.0
  path: ^1.8.3
  retrofit_generator: ^8.1.0
  riverpod_generator: ^2.3.11
  very_good_analysis: ^5.1.0

dependency_overrides:
  # hive легко может поломать базу на устройстве, поэтому обновлять нужно точечно
  # после проверок
  build_runner: 2.4.8
  go_router: 12.1.3
  hive: 2.2.3
  hive_flutter: 1.1.0
  hive_generator: 2.0.0
  meta: 1.10.0
  riverpod_analyzer_utils: 0.5.1 # transitive. 0.5.2 ломает все
  riverpod_annotation: 2.3.5
  riverpod_generator: 2.3.11


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/




          
